chore: split version increase from version gathering and added tag build

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -74,13 +74,11 @@ runs:
         echo env=$(echo '${{ toJSON(env) }}' | jq -r '.')
 
     - name: Increase Versions
-      id: increase_versions_info
       if: ${{ steps.version_info.outputs.increment }}
       shell: bash
       run: |
         workspaces_string="${{ inputs.workspaces }}"
         version_files_string="${{ inputs.version_files }}"
-        versions_array=()
 
         IFS=',' read -r -a workspace_array <<< "$workspaces_string"
         IFS=',' read -r -a version_file_array <<< "$version_files_string"
@@ -92,30 +90,103 @@ runs:
             echo "- testing version file $version_file"
             if [[ -f "$version_file" && "$version_file" == "package.json" ]]; then
               echo "increasing version in $version_file"
-              ${{ env.RELEASEIT }}
-
-              version=$(cat package.json | jq -r '.version')
+              case $version_file in
+                package.json)
+                  ${{ env.RELEASEIT }}
+                  ;;
+                version|VERSION|version.txt|VERSION.txt)
+                  version=$(cat $version_file)
+                  version=${version:-0.0.0}
+                  ${{ env.RELEASEIT }} --pre-changelog "VERSION=$version" --post-changelog "echo $VERSION > $version_file"
+                *)
+                  echo "::error:: Unsupported version file: $version_file"
+                  exit 1
+              esac
               echo "version increased to $version"
-              versions_array+=($version)
             fi
           done
           cd ${{ github.workspace }}
           echo "::endgroup::"
         done
 
+    - name: Increase Versions
+      id: increase_versions_info
+      shell: bash
+      run: |
+        workspaces_string="${{ inputs.workspaces }}"
+        version_files_string="${{ inputs.version_files }}"
+        versions_array=()
+
+        IFS=',' read -r -a workspace_array <<< "$workspaces_string"
+        IFS=',' read -r -a version_file_array <<< "$version_files_string"
+
+        for workspace in "${workspace_array[@]}"; do
+          cd $workspace
+          for version_file in "${version_file_array[@]}"; do
+            if [[ -f "$version_file" && "$version_file" == "package.json" ]]; then
+              echo "increasing version in $version_file"
+              case $version_file in
+                package.json)
+                  version=$(cat package.json | jq -r '.version')
+                  ;;
+                version|VERSION|version.txt|VERSION.txt)
+                  version=$(cat $version_file)
+                *)
+                  echo "::error:: Unsupported version file: $version_file"
+                  exit 1
+              esac
+              versions_array+=($version)
+            fi
+          done
+          cd ${{ github.workspace }}
+        done
+
         IFS=',' versions_string="${versions_array[*]}"
         echo "versions=$versions_string"
         echo "versions=$versions_string" >> $GITHUB_OUTPUT
 
-    - name: Create version branch
-      if: ${{ ! inputs.no_pr && ! startsWith(steps.git_info.outputs.pr_message, 'chore: version merge') }}
+    - name: Prepare Tag
+      if: ${{ steps.increase_versions_info.outputs.versions }}
       shell: bash
       run: |
-        version_branch="version_${{ steps.version_info.outputs.version }}"
-        git checkout -b $version_branch
+        workspaces_string="${{ inputs.workspaces }}"
+        versions_string='${{ steps.increase_versions_info.outputs.versions }}'
 
-        git add .
-        git commit -am "chore: version merge ${{ steps.version_info.outputs.version }}"
-        #git push origin $version_branch
+        IFS=',' read -r -a workspaces_array <<< "$workspaces_string"
+        IFS=',' read -r -a versions_array <<< "$versions_string"
 
-        #gh
+        tag="v${versions_array[0]}"
+
+        if [[ ${#versions_array[@]} -gt 1 ]]; then
+          versions_array=("${versions_array[@]:1}")
+          workspaces_array=("${workspaces_array[@]:1}")
+
+          for (( i=0; i<${#versions_array[@]}; i++ )); do
+            tag="${tag}--${workspaces_array[$i]}@${versions_array[$i]}"
+          done
+        fi
+
+        echo "tag=$tag"
+        echo "tag=$tag" >> $GITHUB_OUTPUT
+
+    # - name: Create version branch
+    #   if: ${{ steps.increase_version_info.outputs.versions && ! inputs.no_pr }}
+    #   shell: bash
+    #   run: |
+    #     version_branch="version_${{ steps.version_info.outputs.version }}"
+    #     git checkout -b $version_branch
+    #
+    #     git add .
+    #     git commit -am "chore: version merge ${{ steps.version_info.outputs.version }}"
+    #     #git push origin $version_branch
+    #
+    #     #gh
+    #
+    # # TODO: add step for merging version into main, which also needs to create the tag
+    #
+    # - name: Commit version
+    #   if: ${{ steps.increase_version_info.outputs.versions && inputs.no_pr }}
+    #   shell: bash
+    #   run: |
+    #     git add .
+    #     git commit -am "chore: version released ${{ steps.version_info.outputs.versions }}
