chore: build version list 1728885304

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -160,44 +160,44 @@ runs:
           echo '::endgroup::'
         done
 
-    # - name: Increase Versions
-    #   id: increase_versions_info
-    #   shell: bash
-    #   run: |
-    #     workspaces_string="${{ inputs.workspaces }}"
-    #     version_files_string="${{ inputs.version_files }}"
-    #     versions_array=()
-    #
-    #     IFS=',' read -r -a workspace_array <<< "$workspaces_string"
-    #     IFS=',' read -r -a version_file_array <<< "$version_files_string"
-    #
-    #     for workspace in "${workspace_array[@]}"; do
-    #       cd $workspace
-    #       for version_file in "${version_file_array[@]}"; do
-    #         if [[ -f "$version_file" && "$version_file" == "package.json" ]]; then
-    #           echo "increasing version in $version_file"
-    #           case $version_file in
-    #             package.json)
-    #               version=$(cat package.json | jq -r '.version')
-    #               ;;
-    #             version|VERSION|version.txt|VERSION.txt)
-    #               version=$(cat $version_file)
-    #               ;;
-    #             *)
-    #               echo "::error:: Unsupported version file: $version_file"
-    #               exit 1
-    #           esac
-    #           versions_array+=($version)
-    #         fi
-    #       done
-    #       cd ${{ github.workspace }}
-    #     done
-    #
-    #     IFS=',' versions_string="${versions_array[*]}"
-    #     echo "versions=$versions_string"
-    #     echo "versions=$versions_string" >> $GITHUB_OUTPUT
-    #
+    - name: Build Versions List
+      id: versions_info
+      shell: bash
+      run: |
+        workspaces_string="${{ inputs.workspaces }}"
+        version_files_string="${{ inputs.version_files }}"
+        versions_array=()
+
+        IFS=',' read -r -a workspace_array <<< "$workspaces_string"
+        IFS=',' read -r -a version_file_array <<< "$version_files_string"
+
+        for ((i=0; i<${#workspaces_array[@]}; i++)); do
+          workspace=${workspace_array[$i]}
+          version_file=${version_files_array[$i]}
+          cd $workspace
+
+          case $version_file in
+            package.json)
+              version=$(cat package.json | jq -r '.version')
+              ;;
+            version|VERSION|version.txt|VERSION.txt)
+              version=$(cat $version_file)
+              ;;
+            *)
+              echo "::error:: Unsupported version file: $version_file"
+              exit 1
+            esac
+            versions_array+=($version)
+
+          cd ${{ github.workspace }}
+        done
+
+        IFS=',' versions_string="${versions_array[*]}"
+        echo "versions=$versions_string"
+        echo "versions=$versions_string" >> $GITHUB_OUTPUT
+
     # - name: Prepare Tag
+    #   id: tag_info
     #   if: ${{ steps.increase_versions_info.outputs.versions }}
     #   shell: bash
     #   run: |
