chore: from scratch 1729547758

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -91,7 +91,7 @@ runs:
         for ((i=0; i<${#workspaces_array[@]}; i++)); do
           workspace=${workspaces_array[$i]}
           version_file=${version_files_array[$i]}
-          echo "testing workspace '$workspace' for changes"
+          echo "::group::testing workspace '$workspace' for changes"
 
           changed_files=$(git diff --name-only "${{ steps.git_info.outputs.last_tag }}" HEAD -- "$workspace")
           changed=0
@@ -115,6 +115,10 @@ runs:
             version|VERSION|version.txt|VERSION.txt)
               version=$(cat $version_file)
               ;;
+            *)
+              echo "::error:: Unsupported version file: $version_file"
+              exit 1
+              ;;
           esac
           version=${version:-0.0.0}
           cd ${{ github.workspace }}
@@ -122,6 +126,8 @@ runs:
           packages=$(echo "$packages" | jq --arg pt "$workspace" --arg v "$version" \
             --arg vf "$version_file" --argjson ch "$changed" \
             '. += [{"path": $pt, "version_file": $vf, "version": $v, "changed": $ch}]')
+
+          echo "::endgroup::"
         done
 
         packages_json=$(echo "$packages" | jq -c '.')
@@ -158,8 +164,6 @@ runs:
       if: ${{ github.event_name == 'push' && steps.version_info.outputs.increment && steps.workspaces_info.outputs.packages != '[]' }}
       shell: bash
       run: |
-        set -ex
-
         ws_regex='^([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z.-]+))?(?:\+([0-9A-Za-z.-]+))?$'
         # loop over all packages
         echo '${{ steps.workspaces_info.outputs.packages }}' | jq -c '.[]' | while read ws; do
@@ -252,7 +256,7 @@ runs:
               echo $version > $ws_version_file
               ;;
             *)
-              echo "Invalid version file"
+              echo "::error:: Unsupported version file: $version_file"
               exit 1
               ;;
           esac
@@ -262,154 +266,155 @@ runs:
         done
 
     # TODO: add a step to build changelogs per workspace
-    #
-    # - name: Build Versions List
-    #   if: ${{ github.event_name == 'push' }}
-    #   id: versions_info
-    #   shell: bash
-    #   run: |
-    #     workspaces_string="${{ inputs.workspaces }}"
-    #     version_files_string="${{ inputs.version_files }}"
-    #     versions_array=()
-    #
-    #     IFS=',' read -r -a workspaces_array <<< "$workspaces_string"
-    #     IFS=',' read -r -a version_files_array <<< "$version_files_string"
-    #
-    #     for ((i=0; i<${#workspaces_array[@]}; i++)); do
-    #       workspace=${workspaces_array[$i]}
-    #       version_file=${version_files_array[$i]}
-    #       cd $workspace
-    #
-    #       case $version_file in
-    #         package.json)
-    #           version=$(cat package.json | jq -r '.version')
-    #           ;;
-    #         go.mod)
-    #           version=$(cat go.mod | sed -n 's/^module.*v\([0-9]\+\.[0-9]\+\.[0-9]\+\)/\1/p')
-    #           ;;
-    #         version|VERSION|version.txt|VERSION.txt)
-    #           version=$(cat $version_file)
-    #           ;;
-    #         *)
-    #           echo "::error:: Unsupported version file: $version_file"
-    #           exit 1
-    #       esac
-    #         versions_array+=($version)
-    #
-    #       cd ${{ github.workspace }}
-    #     done
-    #
-    #     IFS=',' versions_string="${versions_array[*]}"
-    #     echo "versions=$versions_string"
-    #     echo "versions=$versions_string" >> $GITHUB_OUTPUT
-    #
-    # - name: Prepare Tag
-    #   id: tag_info
-    #   if: ${{ github.event_name == 'push' && steps.versions_info.outputs.versions }}
-    #   shell: bash
-    #   run: |
-    #     workspaces_string="${{ inputs.workspaces }}"
-    #     version_files_string="${{ inputs.version_files }}"
-    #     versions_string='${{ steps.versions_info.outputs.versions }}'
-    #
-    #     IFS=',' read -r -a workspaces_array <<< "$workspaces_string"
-    #     IFS=',' read -r -a version_files_array <<< "$version_files_string"
-    #     IFS=',' read -r -a versions_array <<< "$versions_string"
-    #
-    #     tag="v${versions_array[0]}"
-    #
-    #     if [[ ${#versions_array[@]} -gt 1 ]]; then
-    #       workspaces_array=("${workspaces_array[@]:1}")
-    #       version_files_array=("${version_files_array[@]:1}")
-    #       versions_array=("${versions_array[@]:1}")
-    #
-    #       for (( i=0; i<${#versions_array[@]}; i++ )); do
-    #         workspace=${workspaces_array[$i]}
-    #         version_file=${version_files_array[$i]}
-    #         cd $workspace
-    #         workspace_name=$workspace
-    #
-    #         case $version_file in
-    #           package.json)
-    #             workspace_name=$(cat package.json | jq -r '.name')
-    #             ;;
-    #         esac
-    #         tag="${tag}_${workspace_name}${versions_array[$i]}"
-    #         #tag="${tag}_$(date +%s)"
-    #
-    #         cd ${{ github.workspace }}
-    #       done
-    #     fi
-    #
-    #     echo "tag=$tag"
-    #     echo "tag=$tag" >> $GITHUB_OUTPUT
-    #
-    # - name: Set up Git
-    #   if: ${{ github.event_name == 'push' }}
-    #   shell: bash
-    #   run: |
-    #     git config user.name "GitHub Actions"
-    #     git config user.email "actions@github.com"
-    #     git config --global --add safe.directory "$GITHUB_WORKSPACE"
-    #     git remote set-url origin https://x-access-token:${{ inputs.github_token }}@github.com/${{ github.repository }}.git
-    #
-    #     pwd
-    #     ls -la .
-    #     git remote show origin
-    #
-    # - name: Create Version Branch
-    #   env:
-    #     GH_TOKEN: ${{ inputs.github_token }}
-    #   id: version_branch
-    #   if: ${{ github.event_name == 'push' && steps.version_info.outputs.increment && steps.versions_info.outputs.versions && ! inputs.no_pr }}
-    #   shell: bash
-    #   run: |
-    #     tag="${{ steps.tag_info.outputs.tag }}"
-    #     tag=$(echo $tag | sed -e 's/[^a-zA-Z0-9]/_/g')
-    #     version_branch="version_${tag}"
-    #     echo "version_branch=${version_branch}" >> $GITHUB_OUTPUT
-    #
-    #     # Check if there are changes before creating a branch and committing
-    #     if [[ -n "$(git status --porcelain)" ]]; then
-    #       git checkout -b $version_branch
-    #       git add .
-    #       git commit -am "chore: ${{ inputs.version_message }} ${{ steps.tag_info.outputs.tag }}"
-    #       git push origin $version_branch
-    #
-    #       pr_title="${{ inputs.version_message }} ${{ steps.tag_info.outputs.tag }}"
-    #       echo "pr_title=${pr_title}" >> $GITHUB_OUTPUT
-    #       gh pr create --base main --head "$version_branch" --title "$pr_title" --body "New Version Proposed"
-    #
-    #       echo "version_pr=1" >> $GITHUB_OUTPUT
-    #     else
-    #       echo "::warning::No changes to commit. Skipping branch creation."
-    #     fi
-    #
-    # - name: Commit Version
-    #   id: version_commit
-    #   if: ${{ steps.versions_info.outputs.versions && inputs.no_pr }}
-    #   shell: bash
-    #   run: |
-    #     git add .
-    #     git commit -am "chore: ${{ inputs.version_message }} ${{ steps.version_info.outputs.versions }}
-    #
-    #     echo "version_commit=1" >> $GITHUB_OUTPUT
-    #
-    # - name: Create Tag
-    #   id: tag_create_info
-    #   if: ${{ github.event_name == 'push' && ( steps.version_commit.outputs.version_commit || contains(steps.git_info.outputs.commit_message, inputs.version_message) ) }}
-    #   shell: bash
-    #   run: |
-    #     echo "${{ steps.git_info.outputs.commit_message }}"
-    #
-    #     tag="${{ steps.tag_info.outputs.tag }}"
-    #     git fetch --all --tags
-    #
-    #     # Ensure the tag doesn't already exist
-    #     if git rev-parse "$tag" >/dev/null 2>&1; then
-    #       echo "::error::Tag $tag already exists. Skipping tag creation."
-    #       exit 1
-    #     else
-    #       git tag "$tag"
-    #       git push origin "$tag"
-    #     fi
+
+    - name: Build Versions List
+      if: ${{ github.event_name == 'push' }}
+      id: versions_info
+      shell: bash
+      run: |
+        workspaces_string="${{ inputs.workspaces }}"
+        IFS=',' read -r -a workspaces_array <<< "$workspaces_string"
+
+        version_files_string="${{ inputs.version_files }}"
+        IFS=',' read -r -a version_files_array <<< "$version_files_string"
+
+        versions_array=()
+
+        for ((i=0; i<${#workspaces_array[@]}; i++)); do
+          workspace=${workspaces_array[$i]}
+          version_file=${version_files_array[$i]}
+          cd $workspace
+
+          case $version_file in
+            package.json)
+              version=$(cat package.json | jq -r '.version')
+              ;;
+            go.mod)
+              version=$(cat go.mod | sed -n 's/^module.*v\([0-9]\+\.[0-9]\+\.[0-9]\+\)/\1/p')
+              ;;
+            version|VERSION|version.txt|VERSION.txt)
+              version=$(cat $version_file)
+              ;;
+            *)
+              echo "::error:: Unsupported version file: $version_file"
+              exit 1
+          esac
+          versions_array+=($version)
+
+          cd ${{ github.workspace }}
+        done
+
+        IFS=',' versions_string="${versions_array[*]}"
+        echo "versions=$versions_string"
+        echo "versions=$versions_string" >> $GITHUB_OUTPUT
+
+    - name: Prepare Tag
+      id: tag_info
+      if: ${{ github.event_name == 'push' && steps.versions_info.outputs.versions }}
+      shell: bash
+      run: |
+        workspaces_string="${{ inputs.workspaces }}"
+        version_files_string="${{ inputs.version_files }}"
+        versions_string='${{ steps.versions_info.outputs.versions }}'
+
+        IFS=',' read -r -a workspaces_array <<< "$workspaces_string"
+        IFS=',' read -r -a version_files_array <<< "$version_files_string"
+        IFS=',' read -r -a versions_array <<< "$versions_string"
+
+        tag="v${versions_array[0]}"
+
+        if [[ ${#versions_array[@]} -gt 1 ]]; then
+          workspaces_array=("${workspaces_array[@]:1}")
+          version_files_array=("${version_files_array[@]:1}")
+          versions_array=("${versions_array[@]:1}")
+
+          for (( i=0; i<${#versions_array[@]}; i++ )); do
+            workspace=${workspaces_array[$i]}
+            version_file=${version_files_array[$i]}
+            cd $workspace
+            workspace_name=$workspace
+
+            case $version_file in
+              package.json)
+                workspace_name=$(cat package.json | jq -r '.name')
+                ;;
+            esac
+            tag="${tag}_${workspace_name}${versions_array[$i]}"
+            #tag="${tag}_$(date +%s)"
+
+            cd ${{ github.workspace }}
+          done
+        fi
+
+        echo "tag=$tag"
+        echo "tag=$tag" >> $GITHUB_OUTPUT
+
+    - name: Set up Git
+      if: ${{ github.event_name == 'push' }}
+      shell: bash
+      run: |
+        git config user.name "GitHub Actions"
+        git config user.email "actions@github.com"
+        git config --global --add safe.directory "$GITHUB_WORKSPACE"
+        git remote set-url origin https://x-access-token:${{ inputs.github_token }}@github.com/${{ github.repository }}.git
+
+        pwd
+        ls -la .
+        git remote show origin
+
+    - name: Create Version Branch
+      env:
+        GH_TOKEN: ${{ inputs.github_token }}
+      id: version_branch
+      if: ${{ github.event_name == 'push' && steps.version_info.outputs.increment && steps.versions_info.outputs.versions && ! inputs.no_pr }}
+      shell: bash
+      run: |
+        tag="${{ steps.tag_info.outputs.tag }}"
+        tag=$(echo $tag | sed -e 's/[^a-zA-Z0-9]/_/g')
+        version_branch="version_${tag}"
+        echo "version_branch=${version_branch}" >> $GITHUB_OUTPUT
+
+        # Check if there are changes before creating a branch and committing
+        if [[ -n "$(git status --porcelain)" ]]; then
+          git checkout -b $version_branch
+          git add .
+          git commit -am "chore: ${{ inputs.version_message }} ${{ steps.tag_info.outputs.tag }}"
+          git push origin $version_branch
+
+          pr_title="${{ inputs.version_message }} ${{ steps.tag_info.outputs.tag }}"
+          echo "pr_title=${pr_title}" >> $GITHUB_OUTPUT
+          gh pr create --base main --head "$version_branch" --title "$pr_title" --body "New Version Proposed"
+
+          echo "version_pr=1" >> $GITHUB_OUTPUT
+        else
+          echo "::warning::No changes to commit. Skipping branch creation."
+        fi
+
+    - name: Commit Version
+      id: version_commit
+      if: ${{ steps.versions_info.outputs.versions && inputs.no_pr }}
+      shell: bash
+      run: |
+        git add .
+        git commit -am "chore: ${{ inputs.version_message }} ${{ steps.version_info.outputs.versions }}
+
+        echo "version_commit=1" >> $GITHUB_OUTPUT
+
+    - name: Create Tag
+      id: tag_create_info
+      if: ${{ github.event_name == 'push' && ( steps.version_commit.outputs.version_commit || contains(steps.git_info.outputs.commit_message, inputs.version_message) ) }}
+      shell: bash
+      run: |
+        echo "${{ steps.git_info.outputs.commit_message }}"
+
+        tag="${{ steps.tag_info.outputs.tag }}"
+        git fetch --all --tags
+
+        # Ensure the tag doesn't already exist
+        if git rev-parse "$tag" >/dev/null 2>&1; then
+          echo "::error::Tag $tag already exists. Skipping tag creation."
+          exit 1
+        else
+          git tag "$tag"
+          git push origin "$tag"
+        fi
